### PR TITLE
Feature/#393 - Fixed Post random order

### LINKED ISSUE #393: Improve order-by functionality to handle random sort
Hi guys!

Blog post random sorting is implemented like this:

```
if ($sortField == 'random') {
    $sortField = Db::raw('RAND()');
}
```

This implementation is not a cross-platform way of doing this. It will fail on SQLite for example:

image

I'll do a PR for this and for sorting logic itself (there's no need in loop there, for example).

### PR DESCRIPTION
**Pull request by GinoPane**
Fixes #393.

Usage of "@" is justified here because we just need to suppress an expected warning for an empty "direction" part which may be skipped due to `listFrontend` scope usage.

`@list($sortField, $sortDirection) = explode(' ', $sort);`

### CODE REVIEW

File: models/Post.php [hunk 1]
```diff
@@ -242,21 +242,16 @@ public function scopeListFrontEnd($query, $options)
...
-
-            if (in_array($_sort, array_keys(self::$allowedSortingOptions))) {
-                $parts = explode(' ', $_sort);
-                if (count($parts) < 2) {
-                    array_push($parts, 'desc');
-                }
-                list($sortField, $sortDirection) = $parts;
-                if ($sortField == 'random') {
-                    $sortField = Db::raw('RAND()');
+        if (in_array($sort, array_keys(self::$allowedSortingOptions))) {
```
Comment (LukeTowers) [inline models/Post.php]: wouldn't `static::$allowedSortingOptions` be better here than `self::` to allow for people overriding the model?

Comment (GinoPane) [reply models/Post.php]: Done

**Comment by GinoPane** [comment]
@LukeTowers what about this one? Your review comment was fixed long ago 😄
